name: Notify Teams on Push

on:
  push:
    branches:
      - '**' # Trigger on all branches

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Push Details
        id: extract_details
        run: |
          echo "PUSHER_NAME=$(jq -r .pusher.name < "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Send Message to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          PUSHER_NAME: ${{ env.PUSHER_NAME }}
          TIMESTAMP: ${{ env.TIMESTAMP }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          COMMIT_ID: ${{ env.COMMIT_ID }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        run: |
          PAYLOAD=$(jq -n \
            --arg title "GitHub Repository Notification" \
            --arg text "**Push Details:**\n- **Pusher Name:** $PUSHER_NAME\n- **Timestamp:** $TIMESTAMP\n- **Branch Name:** $BRANCH_NAME\n- **Commit ID:** $COMMIT_ID\n- **Commit Message:** $COMMIT_MESSAGE" \
            '{ "@type": "MessageCard", "@context": "http://schema.org/extensions", "summary": $title, "title": $title, "text": $text }')

          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"
